# This workflow will do clean build of the docker image

name: Docker Image DEV Build

on:
  push:
    branches: [nic/env/dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "12"

      - name: install
        run: npm ci

      - name: build
        run: npm run build

      - name: "Build:login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build:outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:dev, ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}
          platforms: linux/amd64,linux/arm64,linux/s390x
